# Generated by Django 3.0.8 on 2020-08-02 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200802_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='courses.CourseProvider'),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='categories', to='courses.Course'),
        ),
    ]
