# Generated by Django 3.0.8 on 2020-08-06 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200806_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='courses.Course'),
        ),
    ]
