# Generated by Django 3.0.8 on 2020-08-07 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200806_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersubitem',
            old_name='addcod',
            new_name='add',
        ),
    ]
