# Generated by Django 3.0.8 on 2020-08-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursereviews'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursereviews',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='course-user-compositekey'),
        ),
    ]
