# Generated by Django 3.0.8 on 2020-08-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200811_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereviews',
            name='text',
            field=models.CharField(default='', max_length=256),
        ),
    ]
